site_name: EdgeX Foundry Hands-on Labs
site_author: "kurokobo"
repo_url: https://github.com/kurokobo/edgex-hol-guide

theme:
    name: "material"
    language: "ja"
    palette:
        primary: "grey"
        accent: "blue"

markdown_extensions:
    - admonition
    - codehilite
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.keys
    - toc:
        permalink: true
    - fontawesome_markdown

extra_css:
    - "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    - "css/custom.css"

extra:
    search:
        language: "en, ja"
    social:
        - icon: fontawesome/brands/github-alt
          link: "https://github.com/kurokobo"
        - icon: fontawesome/brands/twitter
          link: "https://twitter.com/kurokobo"

nav:
    - Index: "index.md"
    - Japanese:
        - このガイドについて: "ja/index.md"
        - Fuji リリース向けガイド:
            - Lab 0 - はじめに: "ja/fuji/index.md"
            - Lab 1 - 概要: "ja/fuji/lab-overview.md"
            - Lab 2 - 導入とデータの確認: "ja/fuji/lab-getting-started.md"
            - Lab 3 - デバイスサービスの追加（MQTT）: "ja/fuji/lab-device-service-mqtt.md"
            - Lab 4 - データのエクスポート（MQTT）: "ja/fuji/lab-app-service-export-mqtt.md"
            - Lab 5 - ルールエンジンの利用: "ja/fuji/lab-support-rulesengine.md"
        - Geneva リリース向けガイド:
            - 準備中: "ja/geneva/index.md"
    - English:
        - About this guide: "en/index.md"
        - Guide for Fuji release:
            - Lab 0 - Introduction: "en/fuji/index.md"
            - Lab 1 - Overview: "en/fuji/lab-overview.md"
            - Lab 2 - Getting Started: "en/fuji/lab-getting-started.md"
            - Lab 3 - Adding a Device Service for MQTT: "en/fuji/lab-device-service-mqtt.md"
            - Lab 4 - Exporting data to MQTT: "en/fuji/lab-app-service-export-mqtt.md"
            - Lab 5 - Using Rules Engine: "en/fuji/lab-support-rulesengine.md"
        - Guide for Geneva release:
            - WIP: "en/geneva/index.md"